apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ambassador-operator-crds.yaml
- ambassador-operator.yaml
#- amb-install.yaml
- ambassador.yaml
- 2048-deployment.yaml
- 2048-namespace.yaml
- 2048-service.yaml

#- manespace-ambassador.yaml
#- ambassador-crds.yaml
#- ambassador-rbac.yaml

